version: '3.3'

services:
  db:
    image: postgres:12.4
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  backend:
    image: shanik92/foodgram-beckend:v5.3
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  frontend:
    image: shanik92/foodgram-frontend:v3.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
